# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-13 02:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField(blank=True, help_text='Write your comment.')),
                ('image', models.ImageField(blank=True, upload_to='profile_image')),
                ('video', models.URLField(blank=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Your post title.', max_length=200)),
                ('context', models.TextField(blank=True, help_text='What is in your mind?')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, upload_to='profile_image')),
                ('video', models.URLField(blank=True)),
                ('PostType', models.CharField(choices=[('---', '---'), ('clubinfo', 'ClubInfo'), ('courseinfo', 'CourseInfo'), ('lookforride', 'FreeRide'), ('tutor', 'TutorInfo'), ('rent', 'RentInfo')], default='---', max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('location', models.CharField(default='', max_length=100)),
                ('website', models.URLField(default='')),
                ('description', models.CharField(default='', help_text='Describe yourself.', max_length=100)),
                ('phone', models.IntegerField(default=0)),
                ('userid', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular user.', primary_key=True, serialize=False)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='profile_image')),
                ('studentID', models.IntegerField(default=0, help_text='Umass studentID.')),
                ('grade', models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior')], default='FRESHMAN', max_length=2)),
                ('major', models.CharField(help_text='Please enter your major.', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='InfoTrack.Post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
